<?php

namespace Database\Seeders;

use App\Models\EmployerPlan;
use Illuminate\Database\Seeder;

class EmployerPlanSeeder extends Seeder
{
    public function run(): void
    {
        $plans = [
            [
                'slug' => 'hiring-launch',
                'tier' => 'Money Back Program',
                'name' => 'Money Back Hiring Program',
                'tagline' => 'Dedicated hiring support with up to 15 qualified interviews in 30 days — or your onboarding fee back.',
                'price_inr' => 10000,
                'price_sub' => 'one-time onboarding + GST',
                'cta' => 'Start Hiring Program',
                'is_popular' => false,
                'is_custom_price' => false,
                'is_active' => true,
                'sort_order' => 0,
                'billing_period' => 'one_time_30d',
                'talent_pool_access' => 'limited',
                'job_credits_included' => 2,
                'unlimited_profile_unlocks' => false,
                'max_active_jobs' => 2,
                'features' => [
                    'One-Time Onboarding Fee: ₹10,000 + GST',
                    'Valid for 2 Active Job Openings',
                    'Program Duration: 30 Days',
                    'Dedicated Hiring Success Manager',
                    'AI-Powered Candidate Matching',
                    'Resume Screening & Shortlisting',
                    'Active Candidate Sourcing',
                    'Candidate Validation Calls',
                    'Interview Scheduling Support',
                    'Candidate Status Tracking',
                    'Weekly Hiring Progress Report',
                    'Employer Hiring Dashboard',
                    'Email & WhatsApp Support',
                    'No Monthly Subscription',
                    'No Placement Commission',
                ],
                'extras' => [
                    'is_launch_offer' => true,
                    'is_money_back_program' => true,
                    'duration' => '30 Days',
                    'duration_days' => 30,
                    'gst_note' => '+ GST applicable',
                    'highlight_stats' => [
                        ['value' => '15', 'label' => 'Qualified interviews', 'icon' => 'mdi-account-check-outline'],
                        ['value' => '30', 'label' => 'Day program', 'icon' => 'mdi-calendar-clock'],
                        ['value' => '2', 'label' => 'Active jobs', 'icon' => 'mdi-briefcase-outline'],
                        ['value' => '100%', 'label' => 'Money back promise', 'icon' => 'mdi-shield-check-outline'],
                    ],
                    'sections' => [
                        [
                            'title' => 'Plan Details',
                            'icon' => 'mdi-clipboard-list-outline',
                            'accent' => 'teal',
                            'items' => [
                                'One-Time Onboarding Fee: ₹10,000 + GST',
                                'Valid for 2 Active Job Openings',
                                'Program Duration: 30 Days',
                                'Dedicated Hiring Success Manager',
                                'AI-Powered Candidate Matching',
                                'Resume Screening & Shortlisting',
                                'Active Candidate Sourcing',
                                'Candidate Validation Calls',
                                'Interview Scheduling Support',
                                'Candidate Status Tracking',
                                'Weekly Hiring Progress Report',
                                'Employer Hiring Dashboard',
                                'Email & WhatsApp Support',
                                'No Monthly Subscription',
                                'No Placement Commission',
                            ],
                        ],
                        [
                            'title' => 'Hiring Commitment',
                            'icon' => 'mdi-handshake-outline',
                            'accent' => 'blue',
                            'items' => [
                                'Up to 15 Qualified Interview Opportunities',
                                'Delivery within 30 Days',
                                'Profiles shared only after screening',
                                'Continuous sourcing throughout the program',
                                'Dedicated hiring support until program completion',
                            ],
                        ],
                        [
                            'title' => 'Employer Responsibilities',
                            'icon' => 'mdi-account-tie-outline',
                            'accent' => 'slate',
                            'items' => [
                                'Share complete Job Description',
                                'Share salary and hiring details',
                                'Schedule interviews within agreed timelines',
                                'Provide interview feedback within 48 hours',
                                'Keep the position active during the program',
                                'No major changes in JD, salary or location after onboarding',
                            ],
                        ],
                        [
                            'title' => 'Program Benefits',
                            'icon' => 'mdi-star-circle-outline',
                            'accent' => 'gold',
                            'items' => [
                                'Faster Hiring Process',
                                'Reduced Hiring Cost',
                                'Access to Pre-Screened Candidates',
                                'AI + Human Recruitment',
                                'Dedicated Hiring Support',
                                'Transparent Hiring Process',
                                'Risk-Free Engagement',
                                'Money Back Assurance',
                            ],
                        ],
                    ],
                    'money_back_promise' => 'If Hirevoo fails to deliver the committed interview opportunities within 30 days, the onboarding fee will be refunded, provided the employer has fulfilled all program terms and responsibilities.',
                ],
            ],
            [
                'slug' => 'starter',
                'tier' => 'Tier 01',
                'name' => 'Starter',
                'tagline' => 'Ideal for small businesses & early-stage startups testing the market.',
                'price_inr' => 4999,
                'price_sub' => 'per month, billed monthly',
                'cta' => 'Get Started',
                'is_popular' => false,
                'is_custom_price' => false,
                'is_active' => true,
                'sort_order' => 1,
                'billing_period' => 'monthly',
                'talent_pool_access' => 'limited',
                'job_credits_included' => 0,
                'unlimited_profile_unlocks' => false,
                'max_active_jobs' => 3,
                'features' => [
                    '3 Active Job Postings',
                    'Candidate Dashboard',
                    'Basic Candidate Filtering',
                    'Limited Resume Database Access',
                    'Email Support',
                ],
            ],
            [
                'slug' => 'growth',
                'tier' => 'Tier 02',
                'name' => 'Growth',
                'tagline' => 'Built for growing startups & SMEs ready to hire with speed and precision.',
                'price_inr' => 14999,
                'price_sub' => 'per month, billed monthly',
                'cta' => 'Start Hiring Smarter',
                'is_popular' => true,
                'is_custom_price' => false,
                'is_active' => true,
                'sort_order' => 2,
                'billing_period' => 'monthly',
                'talent_pool_access' => 'full',
                'job_credits_included' => 50,
                'unlimited_profile_unlocks' => true,
                'max_active_jobs' => 10,
                'features' => [
                    '10 Active Job Postings',
                    'AI Match Scoring',
                    'Referral-Backed Candidates',
                    'Priority Candidate Visibility',
                    'Assisted Candidate Shortlisting',
                    'Full Resume Database Access',
                    'Employer Branding',
                    'Hiring Analytics Dashboard',
                    'WhatsApp Support',
                ],
            ],
            [
                'slug' => 'scale',
                'tier' => 'Tier 03',
                'name' => 'Scale',
                'tagline' => 'Designed for high-growth companies with fast, volume hiring demands.',
                'price_inr' => 39999,
                'price_sub' => 'per month, billed monthly',
                'cta' => 'Scale Your Team',
                'is_popular' => false,
                'is_custom_price' => false,
                'is_active' => true,
                'sort_order' => 3,
                'billing_period' => 'monthly',
                'talent_pool_access' => 'full',
                'job_credits_included' => 50,
                'unlimited_profile_unlocks' => false,
                'max_active_jobs' => 50,
                'features' => [
                    '50 Active Job Postings',
                    '50 Job Posting Credits Included',
                    'Dedicated Hiring Manager',
                    'Priority Referrals',
                    'Candidate Screening',
                    'Interview Coordination',
                    'Advanced Analytics',
                    'ATS Access',
                    'Premium Employer Branding',
                    'Dedicated Account Support',
                ],
            ],
            [
                'slug' => 'enterprise',
                'tier' => 'Tier 04',
                'name' => 'Enterprise',
                'tagline' => 'For large organizations needing full-suite recruitment infrastructure.',
                'price_inr' => null,
                'price_sub' => 'tailored to your requirements',
                'cta' => 'Talk to Sales',
                'is_popular' => false,
                'is_custom_price' => true,
                'is_active' => true,
                'sort_order' => 4,
                'billing_period' => 'monthly',
                'talent_pool_access' => 'full',
                'job_credits_included' => null,
                'unlimited_profile_unlocks' => true,
                'max_active_jobs' => null,
                'features' => [
                    'Unlimited Hiring',
                    'Campus & Bulk Hiring',
                    'Recruitment Process Outsourcing (RPO)',
                    'HRMS Access',
                    'Dedicated Recruitment Team',
                    'API Integrations',
                    'Custom Analytics',
                    'Dedicated Success Manager',
                ],
            ],
        ];

        foreach ($plans as $plan) {
            EmployerPlan::query()->updateOrCreate(
                ['slug' => $plan['slug']],
                $plan
            );
        }

        \Illuminate\Support\Facades\Cache::forget('employer_plans.catalog');
    }
}
