<?php

return [
    'hero' => [
        'badge' => 'Pricing Plans 2025',
        'title' => 'Transparent Pricing.',
        'title_highlight' => 'Hiring Results.',
        'subtitle' => 'From early-stage startups to enterprise organizations — choose the plan that scales with your hiring ambition.',
        'stats' => [
            ['value' => '3,000', 'suffix' => '+', 'label' => 'Verified Candidates'],
            ['value' => '48', 'suffix' => 'h', 'label' => 'Avg. Time to Shortlist'],
            ['value' => '92', 'suffix' => '%', 'label' => 'Client Satisfaction'],
            ['value' => '500', 'suffix' => '+', 'label' => 'Hires Made'],
        ],
    ],

    'plans' => [
        'starter' => [
            'tier' => 'Tier 01',
            'name' => 'Starter',
            'tagline' => 'Ideal for small businesses & early-stage startups testing the market.',
            'price_inr' => 4999,
            'price_sub' => 'per month, billed monthly',
            'cta' => 'Get Started',
            'popular' => false,
            'features' => [
                '3 Active Job Postings',
                'Candidate Dashboard',
                'Basic Candidate Filtering',
                'Limited Resume Database Access',
                'Email Support',
            ],
            'talent_pool_access' => 'limited',
            'database_credits_included' => 0,
            'unlimited_profile_unlocks' => false,
        ],
        'growth' => [
            'tier' => 'Tier 02',
            'name' => 'Growth',
            'tagline' => 'Built for growing startups & SMEs ready to hire with speed and precision.',
            'price_inr' => 14999,
            'price_sub' => 'per month, billed monthly',
            'cta' => 'Start Hiring Smarter',
            'popular' => true,
            'features' => [
                '10 Active Job Postings',
                'AI Match Scoring',
                'Referral-Backed Candidates',
                'Priority Candidate Visibility',
                'Assisted Candidate Shortlisting',
                'Full Resume Database Access',
                'Employer Branding',
                'Hiring Analytics Dashboard',
                'WhatsApp Support',
            ],
            'talent_pool_access' => 'full',
            'database_credits_included' => 50,
            'unlimited_profile_unlocks' => true,
        ],
        'scale' => [
            'tier' => 'Tier 03',
            'name' => 'Scale',
            'tagline' => 'Designed for high-growth companies with fast, volume hiring demands.',
            'price_inr' => 39999,
            'price_sub' => 'per month, billed monthly',
            'cta' => 'Scale Your Team',
            'popular' => false,
            'features' => [
                'Unlimited Job Postings',
                'Dedicated Hiring Manager',
                'Priority Referrals',
                'Candidate Screening',
                'Interview Coordination',
                'Advanced Analytics',
                'ATS Access',
                'Premium Employer Branding',
                'Dedicated Account Support',
            ],
            'talent_pool_access' => 'full',
            'database_credits_included' => 200,
            'unlimited_profile_unlocks' => true,
        ],
        'enterprise' => [
            'tier' => 'Tier 04',
            'name' => 'Enterprise',
            'tagline' => 'For large organizations needing full-suite recruitment infrastructure.',
            'price_inr' => null,
            'price_sub' => 'tailored to your requirements',
            'cta' => 'Talk to Sales',
            'popular' => false,
            'custom_price' => true,
            'features' => [
                'Unlimited Hiring',
                'Campus & Bulk Hiring',
                'Recruitment Process Outsourcing (RPO)',
                'HRMS Access',
                'Dedicated Recruitment Team',
                'API Integrations',
                'Custom Analytics',
                'Dedicated Success Manager',
            ],
            'talent_pool_access' => 'full',
            'database_credits_included' => null,
            'unlimited_profile_unlocks' => true,
        ],
    ],

    'comparison' => [
        'columns' => ['starter', 'growth', 'scale', 'enterprise'],
        'popular_column' => 'growth',
        'rows' => [
            ['category' => 'Job Postings & Visibility', 'cells' => []],
            ['feature' => 'Active Job Postings', 'cells' => ['3', '10', 'Unlimited', 'Unlimited']],
            ['feature' => 'Priority Candidate Visibility', 'cells' => ['—', 'yes', 'yes', 'yes']],
            ['feature' => 'Employer Branding', 'cells' => ['—', 'yes', 'Premium', 'Custom']],
            ['category' => 'AI & Matching', 'cells' => []],
            ['feature' => 'Candidate Dashboard', 'cells' => ['yes', 'yes', 'yes', 'yes']],
            ['feature' => 'AI Match Scoring', 'cells' => ['—', 'yes', 'yes', 'yes']],
            ['feature' => 'Basic Candidate Filtering', 'cells' => ['yes', 'yes', 'yes', 'yes']],
            ['feature' => 'Referral-Backed Candidates', 'cells' => ['—', 'yes', 'Priority', 'Priority']],
            ['feature' => 'Resume Database Access', 'cells' => ['Limited', 'yes', 'yes', 'yes']],
            ['category' => 'Recruitment Operations', 'cells' => []],
            ['feature' => 'Assisted Shortlisting', 'cells' => ['—', 'yes', 'yes', 'yes']],
            ['feature' => 'Candidate Screening', 'cells' => ['—', '—', 'yes', 'yes']],
            ['feature' => 'Interview Coordination', 'cells' => ['—', '—', 'yes', 'yes']],
            ['feature' => 'Dedicated Hiring Manager', 'cells' => ['—', '—', 'yes', 'yes']],
            ['feature' => 'Dedicated Recruitment Team', 'cells' => ['—', '—', '—', 'yes']],
            ['feature' => 'RPO (Recruitment Outsourcing)', 'cells' => ['—', '—', '—', 'yes']],
            ['category' => 'Analytics & Tech', 'cells' => []],
            ['feature' => 'Hiring Analytics Dashboard', 'cells' => ['—', 'yes', 'Advanced', 'Custom']],
            ['feature' => 'ATS Access', 'cells' => ['—', '—', 'yes', 'yes']],
            ['feature' => 'HRMS Access', 'cells' => ['—', '—', '—', 'yes']],
            ['feature' => 'API Integrations', 'cells' => ['—', '—', '—', 'yes']],
            ['category' => 'Support', 'cells' => []],
            ['feature' => 'Email Support', 'cells' => ['yes', 'yes', 'yes', 'yes']],
            ['feature' => 'WhatsApp Support', 'cells' => ['—', 'yes', 'yes', 'yes']],
            ['feature' => 'Dedicated Account Manager', 'cells' => ['—', '—', 'yes', 'yes']],
            ['feature' => 'Dedicated Success Manager', 'cells' => ['—', '—', '—', 'yes']],
        ],
    ],

    'pay_per_hire' => [
        'items' => [
            ['icon' => '🎓', 'icon_class' => 'teal', 'level' => 'Entry Level', 'name' => 'Fresher Hiring', 'price' => 'From <strong>₹10,000</strong> – ₹20,000 per hire'],
            ['icon' => '💼', 'icon_class' => 'blue', 'level' => 'Mid Level', 'name' => 'Experienced Hiring', 'price' => 'From <strong>₹20,000</strong> – ₹50,000 per hire'],
            ['icon' => '📊', 'icon_class' => 'teal', 'level' => 'Manager Level', 'name' => 'Mid Management', 'price' => '<strong>8% – 12%</strong> of Annual CTC'],
            ['icon' => '🏆', 'icon_class' => 'blue', 'level' => 'C-Suite / Senior', 'name' => 'Leadership Hiring', 'price' => '<strong>12% – 18%</strong> of Annual CTC'],
        ],
        'note' => [
            'title' => 'No placement, no fee.',
            'body' => 'Pay Per Hire model ensures you only pay when a successful placement is made. Free to post a requirement — fees apply only on confirmed joining.',
        ],
    ],

    'addons' => [
        ['icon' => '🎓', 'name' => 'Campus Hiring', 'price' => 'Starting at <strong>₹25,000</strong>', 'desc' => 'End-to-end campus recruitment drives — from college partnerships to offer rollouts. Ideal for fresher cohort hiring at scale.'],
        ['icon' => '🌟', 'name' => 'Employer Branding', 'price' => 'Starting at <strong>₹9,999</strong>', 'desc' => 'Build your employer narrative with branded job pages, candidate-facing collateral, and social media hiring assets.'],
        ['icon' => '⚡', 'name' => 'Bulk Hiring', 'price' => '<strong>Custom Pricing</strong>', 'desc' => 'Hire 10, 50, or 500 people — fast. Dedicated sourcing teams, structured assessments, and coordinated onboarding pipelines.'],
        ['icon' => '🔄', 'name' => 'Recruitment Process Outsourcing', 'price' => '<strong>Custom Pricing</strong>', 'desc' => 'Outsource your entire recruitment function to Hirevo. We act as your in-house team — sourcing, screening, and closing.'],
        ['icon' => '🧲', 'name' => 'Talent Pipeline Building', 'price' => '<strong>Custom Pricing</strong>', 'desc' => 'Build a bench of pre-vetted candidates before you even post a role. Stay ahead of growth with always-on talent intelligence.'],
        ['icon' => '🤝', 'name' => 'Not Sure What You Need?', 'price' => "We'll scope it together", 'desc' => 'Our hiring consultants will review your requirements and recommend the right combination of services for your goals and budget.', 'dark' => true, 'link' => 'Schedule a call →'],
    ],

    'cta' => [
        'tag' => 'Free Consultation',
        'title' => 'Book a Free Hiring Consultation',
        'subtitle' => "Talk to a Hirevoo hiring expert. We'll help you find the right plan, define your hiring strategy, and start building your team — faster.",
        'primary' => '📅 Book Free Consultation',
        'secondary' => 'View Case Studies →',
        'trust' => ['No credit card required', '30-minute strategy session', 'Cancel anytime', 'Custom proposal in 24h'],
    ],

    'job_post_credit_cost' => 1,
    'min_search_length' => 2,
];
