<?php

return [
    'hero' => [
        'badge' => 'Pricing Plans 2025',
        'title' => 'Transparent Pricing.',
        'title_highlight' => 'Hiring Results.',
        'subtitle' => 'From early-stage startups to enterprise organizations — choose the plan that scales with your hiring ambition.',
        'stats' => [
            ['value' => '200,000', 'suffix' => '+', 'label' => 'Verified Candidates'],
            ['value' => '48', 'suffix' => 'h', 'label' => 'Avg. Time to Shortlist'],
            ['value' => '96', 'suffix' => '%', 'label' => 'Client Satisfaction'],
            ['value' => '15,000', 'suffix' => '+', 'label' => 'Hires Made'],
        ],
    ],

    // Catalog is stored in `employer_plans` (DB). This block is a fallback if the table is empty.
    'plans' => [
        'hiring-launch' => [
            'tier' => 'Launch Offer',
            'name' => 'Hiring Launch Program',
            'tagline' => 'Launch your first hiring campaign with Hirevoo and experience a smarter way to hire.',
            'price_inr' => 1999,
            'price_sub' => 'one-time · 7 days access',
            'cta' => 'Launch Now',
            'popular' => false,
            'billing_period' => 'one_time_7d',
            'features' => [
                '1 Active Job Posting',
                '7 Days Hiring Launch Access',
                'Hiring Health Score™ Assessment',
                'Dedicated Hiring Consultation',
                'Job Description Review & Optimization',
                'Candidate Sourcing Support',
                'Candidate Management Dashboard Access',
                'Application Tracking',
                'Basic Candidate Filtering',
                'Hiring Performance Review',
                'Hiring Recommendations Report',
                'Priority Email & WhatsApp Support',
                'One-Time Offer for New Companies Only',
                'No Long-Term Commitment Required',
                'Easy Upgrade to Hirevoo Subscription Plans',
            ],
            'extras' => [
                'is_launch_offer' => true,
                'duration' => '7 Days',
                'duration_days' => 7,
                'ideal_for' => [
                    'Startups',
                    'Small Businesses',
                    'First-Time Recruiters',
                    'Companies Hiring for 1–10 Positions',
                ],
                'bonus' => [
                    'Complimentary 30-Minute Hiring Strategy Session',
                    'Personalized Hiring Improvement Recommendations',
                ],
            ],
            'talent_pool_access' => 'limited',
            'job_credits_included' => 1,
            'max_active_jobs' => 1,
            'unlimited_profile_unlocks' => false,
        ],
        'starter' => [
            'tier' => 'Tier 01',
            'name' => 'Starter',
            'tagline' => 'Ideal for small businesses & early-stage startups testing the market.',
            'price_inr' => 4999,
            'price_sub' => 'per month, billed monthly',
            'cta' => 'Get Started',
            'popular' => false,
            'features' => [
                '3 Active Job Postings',
                'Candidate Dashboard',
                'Basic Candidate Filtering',
                'Limited Resume Database Access',
                'Email Support',
            ],
            'talent_pool_access' => 'limited',
            'database_credits_included' => 0,
            'unlimited_profile_unlocks' => false,
        ],
        'growth' => [
            'tier' => 'Tier 02',
            'name' => 'Growth',
            'tagline' => 'Built for growing startups & SMEs ready to hire with speed and precision.',
            'price_inr' => 14999,
            'price_sub' => 'per month, billed monthly',
            'cta' => 'Start Hiring Smarter',
            'popular' => true,
            'features' => [
                '10 Active Job Postings',
                'AI Match Scoring',
                'Referral-Backed Candidates',
                'Priority Candidate Visibility',
                'Assisted Candidate Shortlisting',
                'Full Resume Database Access',
                'Employer Branding',
                'Hiring Analytics Dashboard',
                'WhatsApp Support',
            ],
            'talent_pool_access' => 'full',
            'database_credits_included' => 50,
            'unlimited_profile_unlocks' => true,
        ],
        'scale' => [
            'tier' => 'Tier 03',
            'name' => 'Scale',
            'tagline' => 'Designed for high-growth companies with fast, volume hiring demands.',
            'price_inr' => 39999,
            'price_sub' => 'per month, billed monthly',
            'cta' => 'Scale Your Team',
            'popular' => false,
            'features' => [
                '50 Active Job Postings',
                '50 Job Posting Credits Included',
                'Dedicated Hiring Manager',
                'Priority Referrals',
                'Candidate Screening',
                'Interview Coordination',
                'Advanced Analytics',
                'ATS Access',
                'Premium Employer Branding',
                'Dedicated Account Support',
            ],
            'talent_pool_access' => 'full',
            'job_credits_included' => 50,
            'database_credits_included' => 50,
            'max_active_jobs' => 50,
            'unlimited_profile_unlocks' => false,
        ],
        'enterprise' => [
            'tier' => 'Tier 04',
            'name' => 'Enterprise',
            'tagline' => 'For large organizations needing full-suite recruitment infrastructure.',
            'price_inr' => null,
            'price_sub' => 'tailored to your requirements',
            'cta' => 'Talk to Sales',
            'popular' => false,
            'custom_price' => true,
            'features' => [
                'Unlimited Hiring',
                'Campus & Bulk Hiring',
                'Recruitment Process Outsourcing (RPO)',
                'HRMS Access',
                'Dedicated Recruitment Team',
                'API Integrations',
                'Custom Analytics',
                'Dedicated Success Manager',
            ],
            'talent_pool_access' => 'full',
            'database_credits_included' => null,
            'unlimited_profile_unlocks' => true,
        ],
    ],

    'comparison' => [
        'columns' => ['hiring-launch', 'starter', 'growth', 'scale', 'enterprise'],
        'popular_column' => 'growth',
        'rows' => [
            ['category' => 'Job Postings & Visibility', 'cells' => []],
            ['feature' => 'Active Job Postings', 'cells' => ['1', '3', '10', '50', 'Unlimited']],
            ['feature' => '7-Day Launch Access', 'cells' => ['yes', '—', '—', '—', '—']],
            ['feature' => 'Priority Candidate Visibility', 'cells' => ['—', '—', 'yes', 'yes', 'yes']],
            ['feature' => 'Employer Branding', 'cells' => ['—', '—', 'yes', 'Premium', 'Custom']],
            ['category' => 'AI & Matching', 'cells' => []],
            ['feature' => 'Candidate Dashboard', 'cells' => ['yes', 'yes', 'yes', 'yes', 'yes']],
            ['feature' => 'Hiring Health Score™', 'cells' => ['yes', '—', '—', '—', '—']],
            ['feature' => 'AI Match Scoring', 'cells' => ['—', '—', 'yes', 'yes', 'yes']],
            ['feature' => 'Basic Candidate Filtering', 'cells' => ['yes', 'yes', 'yes', 'yes', 'yes']],
            ['feature' => 'Referral-Backed Candidates', 'cells' => ['—', '—', 'yes', 'Priority', 'Priority']],
            ['feature' => 'Resume Database Access', 'cells' => ['Limited', 'Limited', 'yes', 'yes', 'yes']],
            ['category' => 'Recruitment Operations', 'cells' => []],
            ['feature' => 'Dedicated Hiring Consultation', 'cells' => ['yes', '—', '—', '—', '—']],
            ['feature' => 'Assisted Shortlisting', 'cells' => ['—', '—', 'yes', 'yes', 'yes']],
            ['feature' => 'Candidate Screening', 'cells' => ['—', '—', '—', 'yes', 'yes']],
            ['feature' => 'Interview Coordination', 'cells' => ['—', '—', '—', 'yes', 'yes']],
            ['feature' => 'Dedicated Hiring Manager', 'cells' => ['—', '—', '—', 'yes', 'yes']],
            ['feature' => 'Dedicated Recruitment Team', 'cells' => ['—', '—', '—', '—', 'yes']],
            ['feature' => 'RPO (Recruitment Outsourcing)', 'cells' => ['—', '—', '—', '—', 'yes']],
            ['category' => 'Analytics & Tech', 'cells' => []],
            ['feature' => 'Hiring Analytics Dashboard', 'cells' => ['—', '—', 'yes', 'Advanced', 'Custom']],
            ['feature' => 'ATS Access', 'cells' => ['—', '—', '—', 'yes', 'yes']],
            ['feature' => 'HRMS Access', 'cells' => ['—', '—', '—', '—', 'yes']],
            ['feature' => 'API Integrations', 'cells' => ['—', '—', '—', '—', 'yes']],
            ['category' => 'Support', 'cells' => []],
            ['feature' => 'Email Support', 'cells' => ['yes', 'yes', 'yes', 'yes', 'yes']],
            ['feature' => 'WhatsApp Support', 'cells' => ['yes', 'yes', 'yes', 'yes', 'yes']],
            ['feature' => 'Dedicated Account Manager', 'cells' => ['—', '—', '—', 'yes', 'yes']],
            ['feature' => 'Dedicated Success Manager', 'cells' => ['—', '—', '—', '—', 'yes']],
        ],
    ],

    'pay_per_hire' => [
        'items' => [
            ['icon' => '🎓', 'icon_class' => 'teal', 'level' => 'Entry Level', 'name' => 'Fresher Hiring', 'price' => 'From <strong>₹10,000</strong> – ₹20,000 per hire'],
            ['icon' => '💼', 'icon_class' => 'blue', 'level' => 'Mid Level', 'name' => 'Experienced Hiring', 'price' => 'From <strong>₹20,000</strong> – ₹50,000 per hire'],
            ['icon' => '📊', 'icon_class' => 'teal', 'level' => 'Manager Level', 'name' => 'Mid Management', 'price' => '<strong>8% – 12%</strong> of Annual CTC'],
            ['icon' => '🏆', 'icon_class' => 'blue', 'level' => 'C-Suite / Senior', 'name' => 'Leadership Hiring', 'price' => '<strong>12% – 18%</strong> of Annual CTC'],
        ],
        'note' => [
            'title' => 'No placement, no fee.',
            'body' => 'Pay Per Hire model ensures you only pay when a successful placement is made. Free to post a requirement — fees apply only on confirmed joining.',
        ],
    ],

    'addons' => [
        ['icon' => '🎓', 'name' => 'Campus Hiring', 'price' => 'Starting at <strong>₹25,000</strong>', 'desc' => 'End-to-end campus recruitment drives — from college partnerships to offer rollouts. Ideal for fresher cohort hiring at scale.'],
        ['icon' => '🌟', 'name' => 'Employer Branding', 'price' => 'Starting at <strong>₹9,999</strong>', 'desc' => 'Build your employer narrative with branded job pages, candidate-facing collateral, and social media hiring assets.'],
        ['icon' => '⚡', 'name' => 'Bulk Hiring', 'price' => '<strong>Custom Pricing</strong>', 'desc' => 'Hire 10, 50, or 500 people — fast. Dedicated sourcing teams, structured assessments, and coordinated onboarding pipelines.'],
        ['icon' => '🔄', 'name' => 'Recruitment Process Outsourcing', 'price' => '<strong>Custom Pricing</strong>', 'desc' => 'Outsource your entire recruitment function to Hirevo. We act as your in-house team — sourcing, screening, and closing.'],
        ['icon' => '🧲', 'name' => 'Talent Pipeline Building', 'price' => '<strong>Custom Pricing</strong>', 'desc' => 'Build a bench of pre-vetted candidates before you even post a role. Stay ahead of growth with always-on talent intelligence.'],
        ['icon' => '🤝', 'name' => 'Not Sure What You Need?', 'price' => "We'll scope it together", 'desc' => 'Our hiring consultants will review your requirements and recommend the right combination of services for your goals and budget.', 'dark' => true, 'link' => 'Schedule a call →'],
    ],

    'cta' => [
        'tag' => 'Free Consultation',
        'title' => 'Book a Free Hiring Consultation',
        'subtitle' => "Talk to a Hirevoo hiring expert. We'll help you find the right plan, define your hiring strategy, and start building your team — faster.",
        'primary' => '📅 Book Free Consultation',
        'secondary' => 'View Case Studies →',
        'trust' => ['No credit card required', '30-minute strategy session', 'Cancel anytime', 'Custom proposal in 24h'],
    ],

    'job_post_credit_cost' => 1,
    /** Talent pool: tokens to view phone / contact for one candidate. */
    'unlock_credit_cost' => max(1, (int) env('TALENT_POOL_VIEW_TOKEN_COST', 1)),
    /** Talent pool: tokens to download one candidate profile (CSV + resume link). */
    'excel_download_credit_cost' => max(1, (int) env('TALENT_POOL_DOWNLOAD_TOKEN_COST', 2)),
    /** Job posting credits granted when an employer account is approved (admin or email verification). */
    'employer_approval_credits' => max(0, (int) env('EMPLOYER_APPROVAL_CREDITS', 1)),
    'min_search_length' => 2,

    /** Months employers can prepay for subscription plans (price = monthly rate × months). */
    'billing_duration_options' => [1, 3, 6, 12],
    'default_billing_months' => 1,

    'checkout' => [
        'mode' => env('PLAN_CHECKOUT_MODE', 'razorpay'),
        'gst_rate' => (float) env('PLAN_GST_RATE', 18),
        'payment_notice' => 'Pay by net banking (NEFT / RTGS / IMPS). Transfer to our bank account and submit your UTR and payment date below.',
        'pending_message' => 'Your plan request is received. We will activate your subscription after payment verification.',
        'success_message' => 'Payment successful! Your plan is now active.',
        /** Abandoned Razorpay checkouts with gateway attempts older than this are released. */
        'stale_razorpay_minutes' => (int) env('PLAN_STALE_RAZORPAY_MINUTES', 60),
        'bank_account' => [
            'bank_name' => 'IDFC FIRST Bank',
            'account_name' => 'HIREVOO MARKETING AND Consultancy pvt. Ltd.',
            'account_number' => '82828095506',
            'ifsc' => 'IDFB0020163',
        ],
    ],
];
