name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.10

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/hirevoo

            git pull origin main

            composer install --no-dev --optimize-autoloader

            php artisan optimize:clear

            php artisan migrate --force

            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Fix Laravel permissions
            sudo chown -R ubuntu:www-data /var/www/hirevoo
            sudo chmod -R 775 storage
            sudo chmod -R 775 bootstrap/cache

            # Ensure log file exists
            sudo touch storage/logs/laravel.log
            sudo chmod 664 storage/logs/laravel.log

            php artisan queue:restart
